import { CommodityDefinition } from './types';

/**
 * 5개 카테고리 12종 원자재 선물 마스터 정의
 */
export const COMMODITY_DEFINITIONS: CommodityDefinition[] = [
  // ── 1. 에너지 (Energy) ──
  {
    id: 'CRUDE_OIL',
    ticker: 'CL',
    name: 'WTI Crude Oil',
    nameKo: 'WTI 원유',
    category: 'energy',
    unit: '배럴 (Barrel)',
    basePrice: 78.50,
    tickSize: 0.01,
    tickValue: 10.0,
    baseVolatility: 0.018, // 1.8%
    drift: 0.0001,
    eventSensitivity: 1.6,
    averageVolume: 5000,
    marginRequirement: 5000,
    description: '글로벌 제조업과 수송의 혈액인 서부 텍사스산 원유 선물',
  },
  {
    id: 'NATURAL_GAS',
    ticker: 'NG',
    name: 'Natural Gas',
    nameKo: '천연가스',
    category: 'energy',
    unit: 'MMBtu',
    basePrice: 2.85,
    tickSize: 0.001,
    tickValue: 10.0,
    baseVolatility: 0.035, // 3.5% (고변동성)
    drift: 0.0001,
    eventSensitivity: 1.8,
    averageVolume: 3500,
    seasonality: {
      period: 120, // 동절기 난방 수요 사이클
      amplitude: 0.15,
      phase: 0,
    },
    marginRequirement: 3000,
    description: '겨울철 난방 및 전력 발전에 핵심적인 헨리허브 천연가스 선물',
  },

  // ── 2. 귀금속 (Precious Metals) ──
  {
    id: 'GOLD',
    ticker: 'GC',
    name: 'Gold',
    nameKo: '금 (Gold)',
    category: 'precious_metals',
    unit: '트로이온스 (oz)',
    basePrice: 2350.0,
    tickSize: 0.10,
    tickValue: 10.0,
    baseVolatility: 0.008, // 0.8% (안전자산 저변동성)
    drift: 0.0002, // 인플레이션 헷지 완만한 상승
    eventSensitivity: 1.2,
    averageVolume: 8000,
    marginRequirement: 8000,
    description: '인플레이션 헷지 및 지정학적 위기 시 대표적인 안전자산',
  },
  {
    id: 'SILVER',
    ticker: 'SI',
    name: 'Silver',
    nameKo: '은 (Silver)',
    category: 'precious_metals',
    unit: '트로이온스 (oz)',
    basePrice: 28.50,
    tickSize: 0.005,
    tickValue: 25.0,
    baseVolatility: 0.015,
    drift: 0.0002,
    eventSensitivity: 1.3,
    averageVolume: 4000,
    marginRequirement: 4000,
    description: '귀금속이자 태양광/전자기기 산업재로 폭넓게 쓰이는 은 선물',
  },

  // ── 3. 산업금속 (Industrial Metals) ──
  {
    id: 'COPPER',
    ticker: 'HG',
    name: 'Copper',
    nameKo: '구리 (닥터 코퍼)',
    category: 'industrial_metals',
    unit: '파운드 (lb)',
    basePrice: 4.45,
    tickSize: 0.0005,
    tickValue: 12.5,
    baseVolatility: 0.012,
    drift: 0.0001,
    eventSensitivity: 1.4,
    averageVolume: 4500,
    marginRequirement: 3500,
    description: '글로벌 실물 경기와 전력 인프라의 척도가 되는 닥터 코퍼',
  },
  {
    id: 'IRON_ORE',
    ticker: 'IO',
    name: 'Iron Ore',
    nameKo: '철광석',
    category: 'industrial_metals',
    unit: '건식 메트릭톤 (dmt)',
    basePrice: 112.0,
    tickSize: 0.10,
    tickValue: 10.0,
    baseVolatility: 0.016,
    drift: 0.0001,
    eventSensitivity: 1.3,
    averageVolume: 3000,
    marginRequirement: 2500,
    description: '건설, 조선, 자동차 등 전방 철강 산업의 기초 원자재',
  },
  {
    id: 'LITHIUM',
    ticker: 'LI',
    name: 'Lithium Carbonate',
    nameKo: '탄산리튬',
    category: 'industrial_metals',
    unit: '톤 (ton)',
    basePrice: 14500.0,
    tickSize: 10.0,
    tickValue: 10.0,
    baseVolatility: 0.025, // 2.5% (배터리 고변동성)
    drift: 0.0002,
    eventSensitivity: 1.7,
    averageVolume: 2000,
    marginRequirement: 6000,
    description: '전기차 2차전지 배터리의 핵심 핵심 원소인 화이트 골드',
  },

  // ── 4. 농산물 (Agriculture) ──
  {
    id: 'WHEAT',
    ticker: 'W',
    name: 'Wheat',
    nameKo: '소맥 (밀)',
    category: 'agriculture',
    unit: '부셸 (bushel)',
    basePrice: 580.0,
    tickSize: 0.25,
    tickValue: 12.5,
    baseVolatility: 0.020,
    drift: 0.0000,
    eventSensitivity: 1.5,
    averageVolume: 4000,
    seasonality: {
      period: 100, // 파종/수확기 주기
      amplitude: 0.08,
      phase: Math.PI / 4,
    },
    marginRequirement: 2000,
    description: '글로벌 식량 안보의 핵심 곡물 (시카고 상품거래소 기준)',
  },
  {
    id: 'SOYBEANS',
    ticker: 'S',
    name: 'Soybeans',
    nameKo: '대두 (콩)',
    category: 'agriculture',
    unit: '부셸 (bushel)',
    basePrice: 1180.0,
    tickSize: 0.25,
    tickValue: 12.5,
    baseVolatility: 0.017,
    drift: 0.0000,
    eventSensitivity: 1.4,
    averageVolume: 4000,
    seasonality: {
      period: 100,
      amplitude: 0.07,
      phase: Math.PI / 3,
    },
    marginRequirement: 2500,
    description: '식용유 및 가축 사료의 주원료인 대두 선물',
  },
  {
    id: 'COFFEE',
    ticker: 'KC',
    name: 'Coffee C',
    nameKo: '커피 원두',
    category: 'agriculture',
    unit: '파운드 (lb)',
    basePrice: 225.0,
    tickSize: 0.05,
    tickValue: 18.75,
    baseVolatility: 0.022,
    drift: 0.0001,
    eventSensitivity: 1.6,
    averageVolume: 2500,
    seasonality: {
      period: 80,
      amplitude: 0.10,
      phase: 0,
    },
    marginRequirement: 3000,
    description: '브라질/베트남 기후에 극도로 민감한 아라비카 커피 원두',
  },

  // ── 5. 축산물 (Livestock) ──
  {
    id: 'LIVE_CATTLE',
    ticker: 'LE',
    name: 'Live Cattle',
    nameKo: '생육우 (소고기)',
    category: 'livestock',
    unit: '파운드 (lb)',
    basePrice: 185.0,
    tickSize: 0.025,
    tickValue: 10.0,
    baseVolatility: 0.011,
    drift: 0.0001,
    eventSensitivity: 1.1,
    averageVolume: 2500,
    seasonality: {
      period: 120,
      amplitude: 0.05,
      phase: Math.PI / 2,
    },
    marginRequirement: 2000,
    description: '미국 비육우 출하 및 육류 소비에 연동되는 생육우 선물',
  },
  {
    id: 'LEAN_HOGS',
    ticker: 'HE',
    name: 'Lean Hogs',
    nameKo: '돈육 (돼지고기)',
    category: 'livestock',
    unit: '파운드 (lb)',
    basePrice: 88.50,
    tickSize: 0.025,
    tickValue: 10.0,
    baseVolatility: 0.019,
    drift: 0.0001,
    eventSensitivity: 1.3,
    averageVolume: 2500,
    seasonality: {
      period: 90,
      amplitude: 0.09,
      phase: Math.PI / 6,
    },
    marginRequirement: 1800,
    description: '여름철 바비큐 수요 및 사료 가격에 반응하는 돈육 선물',
  },
];
