#!/usr/bin/env bash
# =====================================================================
# 무명 거래소 — VM 자체 DB 설치 스크립트 (Ubuntu 22.04+)
#  - Docker / Docker Compose plugin 설치
#  - Postgres 16 + PostgREST 12 + Adminer Compose up
#  - .env 자동 생성 (랜덤 비밀번호/JWT 시크릿)
#  - 엔진/프론트 연결용 anon JWT 자동 발급
# =====================================================================
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$PROJECT_DIR"
chmod -R 755 "$PROJECT_DIR"


echo "================================================================"
echo " 1. Docker / Comose 설치 (apt)"
echo "================================================================"

if ! command -v docker >/dev/null 2>&1; then
  sudo apt-get update -y
  sudo apt-get install -y ca-certificates curl gnupg lsb-release
  sudo install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
    sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
    https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
  sudo apt-get update -y
  sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  sudo usermod -aG docker "$USER"
  echo "  Docker 설치 완료. (그룹 적용을 위해 재로그인 필요할 수 있음)"
else
  echo "  이미 설치됨: $(docker --version)"
fi

echo ""
echo "================================================================"
echo " 2. 방화벽 — PostgREST(3001) 만 외부 개방, DB(5432)/Adminer(8080) 는 로컬"
echo "================================================================"

if command -v ufw >/dev/null 2>&1; then
  sudo ufw allow 22/tcp       || true
  sudo ufw allow 3001/tcp    || true   # PostgREST (프론트/엔진 접속)
  sudo ufw --force enable || true
  echo "  ufw 활성화: 22, 3001 개방 (5432, 8080 은 로컬만)"
else
  echo "  ufw 없음 — 수동으로 방화벽 3001 개방 필요"
fi

echo ""
echo "================================================================"
echo " 3. .env 자동 생성 (랜덤 비밀번호 / JWT 시크릿)"
echo "================================================================"

if [ ! -f "$PROJECT_DIR/.env" ]; then
  PGPW="$(openssl rand -hex 16)"
  JWTSECRET="$(openssl rand -hex 32)"
  cat > "$PROJECT_DIR/.env" <<EOF
# Auto generated by setup.sh
POSTGRES_USER=moo_app
POSTGRES_PASSWORD=$PGPW
POSTGRES_DB=moo
PGRST_JWT_SECRET=$JWTSECRET
EOF
  chmod 600 "$PROJECT_DIR/.env"
  echo "  .env 생성 완료"
else
  echo "  .env 이미 있음 — 재사용"
fi

set -a
source "$PROJECT_DIR/.env"
set +a


echo ""
echo "================================================================"
echo " 4. docker compose up -d"
echo "================================================================"

sudo docker compose pull
sudo docker compose up -d

echo "  대기: DB healthy 까지..."
until sudo docker inspect --format '{{.State.Health.Status}}' moo_DB 2>/dev/null | grep -q healthy; do
  printf '.'
  sleep 3
done
echo ""
echo "  DB 준비 완료."

echo ""
echo "================================================================"
echo " 5. anon / authenticated / postgres 역할 + JWT 권한 세팅"
echo "================================================================"

# Postgres v12 PostgREST 는 더 이상 db-skip-role-jwt-check 같은 옵션이므로,
# anon 역할이 존재하는지 확인. 스키마 01_schema.sql 이 이미 만들었음.
sudo docker compose exec -T db psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "GRANT USAGE ON SCHEMA public TO anon;"

echo "  완료."

echo ""
echo "================================================================"
echo " 6. anon / service_role JWT 발급 (Supabase URL 호환)"
echo "================================================================"

# PostgREST v12 의 anon JWT 형식 (role=anon)
generate_jwt() {
  local ROLE="$1"
  local SECRET="$2"
  # 헤더 / 페이로드 base64url (JSON, no padding)
  local HEADER=$(printf '{"alg":"HS256","typ":"JWT"}' | openssl base64 -A 2>/dev/null | tr '/+' '_-' | tr -d '=')
  local PAYLOAD=$(printf '{"role":"%s","iss":"postgrest","exp":9999999999}' "$ROLE" | openssl base64 -A 2>/dev/null | tr '/+' '_-' | tr -d '=')
  local SIG=$(printf '%s.%s' "$HEADER" "$PAYLOAD" | openssl dgst -sha256 -hmac "$SECRET" -binary | openssl base64 -A 2>/dev/null | tr '/+' '_-' | tr -d '=')
  printf '%s.%s.%s' "$HEADER" "$PAYLOAD" "$SIG"
}

JWTSECRET=$(grep PGRST_JWT_SECRET "$PROJECT_DIR/.env" | cut -d= -f2)
ANON_JWT=$(generate_jwt anon "$JWTSECRET")
SERVICE_JWT=$(generate_jwt service_role "$JWTSECRET")

cat > "$PROJECT_DIR/connection.txt" <<EOF
================================================================
무명 거래소 VM DB — 접속 정보
================================================================

외부에서 접속 (PostgREST REST API):
  URL         : http://$(curl -s ifconfig.me):3001
  ANON KEY    : $ANON_JWT
  SERVICE KEY : $SERVICE_JWT

프론트엔드 / 엔진 .env.local 교체:
  NEXT_PUBLIC_SUPABASE_URL=http://$(curl -s ifconfig.me):3001
  NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON_JWT
  SUPABASE_SERVICE_ROLE_KEY=$SERVICE_JWT

SSH 터널로 Adminer 접근:
  ssh -L 8080:127.0.0.1:8080 user@VM_IP
  브라우저: http://localhost:8080
    시스템: PostgreSQL
    서버  : db
    사용자: moo_app
    DB    : moo
    비밀번호: .env 파일 안의 POSTGRES_PASSWORD

직접 psql (DB 컨테이너 진입):
  sudo docker compose exec db psql -U moo_app -d moo

================================================================
EOF

cat "$PROJECT_DIR/connection.txt"

echo ""
echo "설치 완료. connection.txt 파일에 모든 접속 정보가 저장됨."
echo "이제 로컬 PC 의 프론트/엔진 .env.local 의 SUPABASE_* 환경변수를 위 값으로 교체 후 재배포."